### ISSUE TITLE
[documentation] Username and Password parameter missing from PowerShell Script

### ISSUE THREAD

**Issue by deFr0ggy** [p0dalirius/ExtractBitlockerKeys#2]
Seems like the username and the password parameters are missing from the powershell script. 

![image](https://github.com/p0dalirius/ExtractBitlockerKeys/assets/16836050/8f935e61-f63f-4d1f-9770-c0aa73dbd4ee)

**Comment by p0dalirius** [comment]
Options were changed in https://github.com/p0dalirius/ExtractBitlockerKeys/pull/1 to avoid clear input of user credentials.

**Comment by deFr0ggy** [comment]
Appreciated!
